### ISSUE TITLE
Tailwind

### ISSUE THREAD

**Issue by rithviknishad** [vaidyuti/scramjet-cockpit#1]
- [ ] P0: Configure tailwind for NextJS project.
- [ ] P1: Use **Inter** as sans font from google fonts.
- [ ] P1: Primary color to be [#EEFF41](https://www.tailwindshades.com/#color=65.36842105263159%2C100%2C62.745098039215684&step-up=8&step-down=11&hue-shift=0&name=golden-fizz&base-stop=5&overrides=e30%3D) as follows:
```js
'primary': {
  DEFAULT: '#EEFF41',
  '50': '#FEFFF9',
  '100': '#FDFFE4',
  '200': '#F9FFBB',
  '300': '#F5FF93',
  '400': '#F2FF6A',
  '500': '#EEFF41',
  '600': '#E9FF09',
  '700': '#BDD000',
  '800': '#8A9800',
  '900': '#576000'
},
```
- [ ] P2: Set up light and dark theme support (see dex-portal implementation).
